version: '3.8'

services:
    bot_wars_db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Sqlhaslo123!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Evaluation"
        volumes:
            - bot_wars_db:/var/lib/mssql
    bot_wars_api:
        build:
            context: .
            dockerfile: Communication/api.dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - bot_wars_db
        restart: 
            always
        
    bot_wars_engine:
        build:
            context: .
            dockerfile: Engine/engine.dockerfile
        ports:
            - "7001:8080"
        depends_on:
            - bot_wars_api
    file_gatherer:
        build:
            context: .
            dockerfile: FileGatherer/gatherer.dockerfile
        ports:
            - "7002:8080"
        volumes:
            - file_gatherer:/app/Storage
        
volumes:
    bot_wars_db:
        driver: local
    file_gatherer:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: FileGatherer/Storage