name: Health Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build & Health Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Install dotnet-ef tool
      run: |
        dotnet tool install --global dotnet-ef

    - name: Apply database migrations
      run: |
        dotnet ef database update --project Shared/Shared.csproj --startup-project BotWars/BotWars.csproj

    - name: Running Tests
      run: |
        dotnet test UnitTests/UnitTests.csproj
