name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push docker image for API
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Communication/api.dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bot-wars-api:$(date +%s)

