name: Api Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  TAG: ${{$(date +'%Y-%m-%dT%H:%M:%S')}}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Generate Tag
      run: echo "TAG=$(date +'%y.%m.%d')" >> $GITHUB_ENV

    - name: Get repository name
      id: repo-name
      uses: MariachiBear/get-repo-name-action@v1.1.0
      with:
        string-case: 'lowercase'
      env:
          REPO_NAME: ${{ steps.repo-name.outputs.repository-name }}
      
    - name: Build and Push docker api image to Github Registery
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Communication/api.dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.TAG }}
